trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  - repo: self

variables:
  imagePullSecret: 'regcred'
  containerName: 'crud-cloud'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'projeto-aula-devops-docker'
        repository: 'luisgontarski/projeto-aula-devops'
        command: 'buildAndPush'
        tags: '$(Build.BuildId)'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

    # Criar o container para o BFF com o nome crud-cloud
    - script: |
        docker run --name $(containerName) -d luisgontarski/projeto-aula-devops:$(Build.BuildId)
      displayName: 'Run BFF container crud-cloud'
