resources:
  - repo: self

variables:
  imagePullSecret: 'regcred'
  containerName: 'crud-cloud'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'projeto-aula-devops-docker'
              repository: 'luisgontarski/projeto-aula-devops' 
              command: 'buildAndPush'
              tags: '$(Build.BuildId)'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'myAzureServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Deploying BFF container to Azure Container Apps..."
                az containerapp up --name $(containerName) --resource-group luisedgon --image luisgontarski/projeto-aula-devops:$(Build.BuildId) --target-port 3000
            displayName: 'Deploy to Azure Container Apps'