trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  - repo: self

variables:
  imagePullSecret: 'regcred'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
   
    - task: Docker@2
      inputs:
        containerRegistry: 'Projeto-Aula-Devops-Docker'
        repository: 'luisgontarski/projeto-aula-devops' 
        command: 'buildAndPush'
        tags: '$(Build.BuildId)'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'Projeto-Aula-Devops-Docker'
        repository: 'luisgontarski/projeto-aula-devops' 
        command: 'login'
    
    - script: |
        # Puxar a imagem Docker do registro
        docker pull projeto-aula-devops-docker.azurecr.io/luisgontarski/projeto-aula-devops:$(Build.BuildId)

        # Rodar o container da imagem
        docker run -d -p 8080:80 projeto-aula-devops-docker.azurecr.io/luisgontarski/projeto-aula-devops:$(Build.BuildId)
      displayName: 'Pull and Run Docker container'
