resources:
  - repo: self

variables:
  imagePullSecret: 'regcred'
  containerName: 'crud-cloud'
  imageName: 'luisgontarski/projeto-aula-devops' 

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build BFF
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x' 
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run start  # Inicia a aplicação
            displayName: 'Install Dependencies and Start Application'

          - task: Docker@2
            inputs:
              containerRegistry: 'projeto-aula-devops-docker' 
              repository: '$(imageName)'
              command: 'buildAndPush'
              tags: '$(Build.BuildId)'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'myAzureServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Deploying BFF container to Azure Container Apps..."
                az containerapp up --name $(containerName) --resource-group luisedgon --image $(imageName):$(Build.BuildId) --target-port 3000
            displayName: 'Deploy to Azure Container Apps'
