trigger:
  branches:
    include:
      - main

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build and Push Docker Image
        steps:
          - checkout: self
          
          # Passo opcional para listar arquivos no diretório de origem para depuração
          - script: |
              echo "Listing files in source directory"
              ls -al $(Build.SourcesDirectory)
            displayName: 'List files in source directory'

          - task: Docker@2
            inputs:
              containerRegistry: 'Projeto-Aula-Devops-Docker'  # Nome da conexão de registro de contêiner
              repository: 'luisgontarski/projeto-aula-devops'  # Nome do repositório
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Caminho para o Dockerfile
              tags: '$(Build.BuildId)'  # Tag para a imagem Docker
