trigger:
  - main

pool:
  vmImage: ubuntu-latest

resources:
  - repo: self

variables:
  imagePullSecret: 'regcred'  # Nome do pull secret do seu container registry
  containerName: 'crud-cloud'  # Nome do container que será criado
  containerRegistry: 'projeto-aula-devops-docker'  # Nome do registro de containers
  imageName: 'luisgontarski/projeto-aula-devops'  # Nome da imagem
  imageTag: '$(Build.BuildId)'  # Tag da imagem gerada no build

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(containerRegistry)
        repository: $(imageName)
        command: 'buildAndPush'
        tags: '$(imageTag)'  # Tagging the image with the build ID
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'  # Ensure Docker build context is correct

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy BFF Container
    steps:
    - script: |
        echo "Deploying BFF container to Azure Container Apps..."
        az containerapp update \
          --name $(containerName) \
          --resource-group <resource-group-name> \
          --image $(containerRegistry)/$(imageName):$(imageTag) \
          --cpu 0.5 \
          --memory 1Gi \
          --env-vars PORT=3000  # Exemplo de variável de ambiente (ajustar conforme necessário)
      displayName: 'Deploy to Azure Container Apps'

